services:
  cvss_31:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cvss_31.rule=Host(`localhost`)"
      - "traefik.http.services.cvss_31.loadbalancer.server.port=8080"
    restart: unless-stopped

  traefik:
    image: traefik:v3.3.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
    restart: unless-stopped
